services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: travels-db
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - travels-network
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - travels-network

networks:
  travels-network:
    driver: bridge

volumes:
  postgres: