name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create .env file
        run: |
          echo "PROJECT_NAME=RoutesApi" > .env
          echo "PROJECT_LOCAL_PORT=3006" >> .env
          echo "PROJECT_CONTAINER_PORT=3006" >> .env
          echo "DB_PASSWORD=root" >> .env
          echo "DB_NAME=TravelsDB" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5447" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "PORT=3006" >> .env
          echo "DATABASE_URL=\"postgresql://postgres:root@localhost:5447/TravelsDB?schema=public\"" >> .env

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

      - name: Build project
        run: yarn build

      - name: Start database container
        run: make up-db

      - name: Verify application startup
        env:
          NODE_ENV: production
        run: |
          yarn start
          echo "Application started"

      - name: Stop application
        run: |
          PID=$(pgrep -f "node ./dist/main.js")
          if [ -n "$PID" ]; then
            kill "$PID"
            echo "Application stopped"
          else
            echo "No running application found"
          fi

      - name: Stop database
        run: make down-db
